trigger:
- master

pr: none

pool:
  vmImage: windows-latest

steps:
- task: UseDotNet@2
  displayName: Use dotnet
  inputs:
    packageType: 'runtime'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
    workingDirectory: '$(Pipeline.Workspace)'

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'off'

- task: PublishPipelineArtifact@1
  displayName: Publish artifact
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'