trigger:
- master

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: Use dotnet
  inputs:
    packageType: 'runtime'
    version: '5.x'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
    workingDirectory: '$(Pipeline.Workspace)'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    nobuild: true
    versioningScheme: 'off'
